version: 2 # CircleCI version
jobs:
  test:
    docker:
      - image: circleci/node:latest
    steps:
        - setup_remote_docker
        - run: docker-compose up -d
        - run: ./soft-test.sh
        - store_artifacts:
            path: ~/repo/features/fail-screenshots

workflows:
   version: 2
   test_and_build:
     jobs:
       - test
