version: 2 # CircleCI version
jobs:
  test:
    docker:
      - image: circleci/node:latest
    steps:
        - checkout
        - run: docker-compose up -d
        - run: ./soft-test.sh
        - store_artifacts:
            path: ~/repo/features/fail-screenshots